# Generated by Django 5.2.8 on 2026-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='nom complet')),
                ('situation', models.CharField(blank=True, choices=[('student', 'Étudiant'), ('employed', 'Employé'), ('unemployed', 'Sans emploi')], max_length=20, verbose_name='situation')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='spécialité')),
                ('study_level', models.CharField(blank=True, max_length=100, verbose_name="niveau d'études")),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='poste')),
                ('neighborhood', models.CharField(blank=True, max_length=200, verbose_name='région')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='photo')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motif de rejet')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
    ]
