# Generated by Django 4.2.13 on 2026-05-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'starts_at'], name='event_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='post_status_date_idx'),
        ),
    ]
