# Generated by Django 5.2.8 on 2026-05-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='année')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_mode', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement')], default='cash', max_length=20, verbose_name='mode de paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'cotisation',
                'verbose_name_plural': 'cotisations',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
