# Generated by Django 5.2.8 on 2026-05-17 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='membre'),
        ),
        migrations.AddField(
            model_name='payment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL, verbose_name='validé par'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'year')},
        ),
    ]
