# Generated by Django 4.2.13 on 2026-05-19 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='reçu'),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motif de rejet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='vérifié le'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='vérifié par'),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='soumis le'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='référence transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('sedad', 'Sedad'), ('bimbank', 'BimBank'), ('clique', 'Clique'), ('amanty', 'Amanty'), ('transfer', 'Virement bancaire')], default='cash', max_length=20, verbose_name='mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('submitted', 'Reçu soumis'), ('paid', 'Payé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
